spring:
  application:
    name: spring-blog-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/java_blog_spring?characterEncoding=utf8&useSSL=false
    username: root
    password: ${MYSQL_PASSWORD} # 使用 export MYSQL_PASSWORD='xxx' 来添加环境变量
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:

  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  file:
    name: logs/spring-blog.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i
  level:
    root: info
#    com.example.demo: debug
