spring:
  application:
    name: book-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book_test?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    favicon:
      enable: false
  profiles:  #\u591A\u5E73\u53F0\u914D\u7F6E
    active: dev

mybatis:
  # \u8BBE\u7F6E Mybatis \u7684 xml \u4FDD\u5B58\u8DEF\u5F84
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # \u914D\u7F6E\u6253\u5370 MyBatis \u6267\u884C\u7684 SQL
    map-underscore-to-camel-case: true  #\u81EA\u52A8\u9A7C\u5CF0\u8F6C\u6362

logging:
  file:
    name: logs/springboot.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i
  level:
    root: info
    com.example.demo: debug
